CODE = ../src/code
all: 
	while-test 
	if-number-test


if-number-test:	
	$(CODE) if-number-test.txt
	$(CODE)

if-ineq-test:
	$(CODE) if-ineq-test.txt
	$(CODE)

while-test: 
	$(CODE) while-test.txt
	$(CODE)

for-test:
	$(CODE) for-test.txt
	$(CODE)