/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 37
#line 1 "cParser.leg"

;

#define FILEOUTPUT 1

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#ifndef DEBUG
    #define DEBUG 1
    void debug_log(char *file,int line,const char *format, ...) {
        va_list args;
        va_start(args, format);
        printf("[LOG] %s line %d:\t",file,line);
        vprintf(format, args);  // 可変引数を処理
        printf("\n");
        va_end(args);
    }
    #define DEBUG_LOG(...) debug_log(__FILE__, __LINE__, __VA_ARGS__)

    void debug_error_1ref(char* file,int line,const char *format, ...) {
        va_list args;
        va_start(args, format);
        fprintf(stderr, "[ERROR] %s line %d\n",file,line);
        vfprintf(stderr, format, args);  // エラーメッセージは stderr に出力
        fprintf(stderr, "\n");
        va_end(args);
    }
    #define DEBUG_ERROR(...) debug_error_1ref(__FILE__, __LINE__,__VA_ARGS__)
    #define DEBUG_ERROR_COND(COND,...) ({ \
        if(!(COND)){ \
            debug_error_1ref(__FILE__,__LINE__,__VA_ARGS__);\
        }\
    })
    void debug_error_2ref(char* file1,int line1,char* file2,int line2,const char *format, ...) {
        va_list args;
        va_start(args, format);
        fprintf(stderr, "[ERROR] %s line %d\n",file1,line1);
            fprintf(stderr, "        %s line %d:\t",file2,line2);
        vfprintf(stderr, format, args);  // エラーメッセージは stderr に出力
        fprintf(stderr, "\n");
        va_end(args);
    }
    #define DEBUG_ERROR_REF(...) debug_error_2ref(__FILE__, __LINE__,file,line, __VA_ARGS__)
    #define DEBUG_ERROR_COND_REF(COND,...) ({ \
        if(!(COND)){ \
            debug_error_2ref(__FILE__,__LINE__,file,line,__VA_ARGS__);\
        }\
    })
#endif


FILE* _file_ = NULL;

void _stdout(const char *format, ...){
    va_list args;
    va_start(args, format);
#if FILEOUTPUT
    vfprintf(_file_, format, args);
#else
    vfprintf(stdout, format, args);
#endif
    va_end(args);
}  
#define write(...) _stdout(__VA_ARGS__)

union Token;
typedef union Token Token;
typedef Token *tkn;

typedef enum {Undefined, Contents, Include, Function, Ctype, Symbol, Params, Body, Stmt, Return } type_t;
typedef enum {VOID,CHAR,INT,FLOAT,DOUBLE,} type_c;

char* _void_ = "void";
char* _char_ = "char";
char* _int_ = "int";
char* _float_ = "float";
char* _double_ = "double";

char* CtypeToStr(type_c t){
    switch(t){
        case VOID:return _void_;
        case CHAR:return _char_;
        case INT:return _int_;
        case FLOAT:return _float_;
        case DOUBLE:return _double_;
        default:DEBUG_ERROR("this is not happen!");
    }
    return 0;
}

char* _void_shica_ = "Undefined";
char* _char_shica_ = "Char";
char* _int_shica_ = "Integer";
char* _float_shica_ = "Float";
char* _double_shica_ = "Double";

char* CtypeToShicaStr(type_c t){
    switch(t){
        case VOID:return _void_shica_;
        case CHAR:return _char_shica_;
        case INT:return _int_shica_;
        case FLOAT:return _float_shica_;
        case DOUBLE:return _double_shica_;
        default:DEBUG_ERROR("this is not happen!");
    } 
    return 0;
}

union Token{
    type_t typeT;
    struct Contents{type_t typeT; tkn name; unsigned int size,capacity; tkn *expressions;} Contents;
    struct Include {type_t typeT; tkn header; unsigned custom:1; } Include;
    struct Function{type_t typeT; tkn retType,name,params,body; } Function;
    struct Ctype   {type_t typeT; type_c typeC; } Ctype;
    struct Symbol  {type_t typeT; char* name;   } Symbol;
    struct Params  {type_t typeT; tkn paramsType,paramsName,paramNext;} Params;
    struct Body    {type_t typeT; unsigned int size; tkn *statements;}Body;
    struct Stmt    {type_t typeT; char *stmt;} Stmt;
    struct Return  {type_t typeT; tkn variable;} Return;
};
tkn nil = 0;

tkn _newToken(size_t size,type_t type)
{
    tkn token = calloc(1, size);
    token->typeT = type;
    return token;
}
#define newToken(TYPE)	_newToken(sizeof(struct TYPE), TYPE)

#define getType(T) T->typeT
tkn _check(tkn token,type_t type, char *file, int line)
{
    DEBUG_ERROR_COND_REF(getType(token) == type,"expected type %d got type %d",type,getType(token));
    return token;
}
#if DEBUG
    #define get(PTR, TYPE, FIELD)	(_check((PTR), TYPE, __FILE__, __LINE__)->TYPE.FIELD)
#else
    #define get(PTR, TYPE, FIELD)  (PTR->TYPE.FIELD)
#endif


tkn newCtype(type_c type){
    tkn token = newToken(Ctype);
    token->Ctype.typeC = type;
    return token;
}

tkn newContents(tkn name){
    tkn token = newToken(Contents);
    token->Contents.expressions = 0;
    token->Contents.size = 0;
    token->Contents.name = name;
    return token;
}
tkn appendContents(tkn b,tkn s){
    tkn *ss = get(b, Contents,expressions);
    int  sz = get(b, Contents,size);
    ss = realloc(ss, sizeof(tkn) * (sz + 1));
    ss[sz++] = s;
    get(b, Contents,expressions) = ss;
    get(b, Contents,size) = sz;
    return b;
}

tkn newInclude(tkn header,int isCustom){
    tkn token = newToken(Include);
    token->Include.header = header;
    token->Include.custom = isCustom;
    return token;
}

tkn newSymbol(char* value){
    tkn token = newToken(Symbol);
    token->Symbol.name = strdup(value);
    return token;
}

tkn newFunction(tkn type,tkn name,tkn params,tkn body){
    tkn token = newToken(Function);
    token->Function.retType = type;
    token->Function.name    = name;
    token->Function.params  = params;
    token->Function.body    = body;
    return token;
}

tkn newParams(tkn type,tkn name,tkn prev){
    tkn token = newToken(Params);
    token->Params.paramsType = type;
    token->Params.paramsName = name;
    token->Params.paramNext  = prev;
    return token;
}

tkn revPrams(tkn head){
    tkn tail = nil;
    while(head != nil){
        tkn p = tail;
        tail = head;
        head = head->Params.paramNext;
        tail->Params.paramNext = p;
    }
    return tail;
}

tkn newBody(){
    tkn token = newToken(Body);
    token->Body.size = 0;
    token->Body.statements = 0;
    return token;
}
void bodyAppend(tkn b, tkn s)
{
    tkn *ss = get(b, Body,statements);
    int  sz = get(b, Body,size);
    ss = realloc(ss, sizeof(tkn) * (sz + 1));
    ss[sz++] = s;
    get(b, Body,statements) = ss;
    get(b, Body,size) = sz;
}

tkn newReturn(tkn variable){
    tkn token = newToken(Return);
    token->Return.variable = variable;
    return token; 
}

void printToken(tkn t,int indent){
    switch(getType(t)){
        case Contents:
        case Include:
        case Function:
        case Ctype:
        case Symbol:
        case Params:
        case Body:  
        case Stmt: 
        case Return:
        default:{
            DEBUG_ERROR("this is not happen at printToken");
        }
    }
}

// AFTER PARSE +++++++++++++++++++++++++++++++++++++++++++

tkn* functions = 0;
unsigned int nfunctions = 0;

tkn addFunction(tkn token)
{
    functions   = realloc(functions,   sizeof(*functions)   * (nfunctions + 1));
    return functions[nfunctions++] = token;
}

//+++++++++++++++++++++++++++++++++++++++++++
#define YYPARSE cLangParse // C language parser
#define YYSTYPE tkn
YYSTYPE result;
int i = 0;
// https://programming-place.net/ppp/contents/c/appendix/operation.html

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_blank(yycontext *yy); /* 37 */
YY_RULE(int) yy_space(yycontext *yy); /* 36 */
YY_RULE(int) yy__(yycontext *yy); /* 35 */
YY_RULE(int) yy_alnum(yycontext *yy); /* 34 */
YY_RULE(int) yy_sym(yycontext *yy); /* 33 */
YY_RULE(int) yy_num(yycontext *yy); /* 32 */
YY_RULE(int) yy_alpha(yycontext *yy); /* 31 */
YY_RULE(int) yy_empty(yycontext *yy); /* 30 */
YY_RULE(int) yy_text(yycontext *yy); /* 29 */
YY_RULE(int) yy_RET(yycontext *yy); /* 28 */
YY_RULE(int) yy_RBRA(yycontext *yy); /* 27 */
YY_RULE(int) yy_stmt(yycontext *yy); /* 26 */
YY_RULE(int) yy_mkbody(yycontext *yy); /* 25 */
YY_RULE(int) yy_LBRA(yycontext *yy); /* 24 */
YY_RULE(int) yy_RPAR(yycontext *yy); /* 23 */
YY_RULE(int) yy_COMMA(yycontext *yy); /* 22 */
YY_RULE(int) yy_LPAR(yycontext *yy); /* 21 */
YY_RULE(int) yy_mkNil(yycontext *yy); /* 20 */
YY_RULE(int) yy_SEMI(yycontext *yy); /* 19 */
YY_RULE(int) yy_body(yycontext *yy); /* 18 */
YY_RULE(int) yy_params(yycontext *yy); /* 17 */
YY_RULE(int) yy_type(yycontext *yy); /* 16 */
YY_RULE(int) yy_DQUOTE(yycontext *yy); /* 15 */
YY_RULE(int) yy_RSQ(yycontext *yy); /* 14 */
YY_RULE(int) yy_HEAD(yycontext *yy); /* 13 */
YY_RULE(int) yy_LSQ(yycontext *yy); /* 12 */
YY_RULE(int) yy_INCL(yycontext *yy); /* 11 */
YY_RULE(int) yy_function(yycontext *yy); /* 10 */
YY_RULE(int) yy_RBRACE(yycontext *yy); /* 9 */
YY_RULE(int) yy_exp(yycontext *yy); /* 8 */
YY_RULE(int) yy_LBRACE(yycontext *yy); /* 7 */
YY_RULE(int) yy_symbol(yycontext *yy); /* 6 */
YY_RULE(int) yy_PCENT(yycontext *yy); /* 5 */
YY_RULE(int) yy_eol(yycontext *yy); /* 4 */
YY_RULE(int) yy_define(yycontext *yy); /* 3 */
YY_RULE(int) yy_bln(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_mkNil(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mkNil\n"));
  {
#line 316
   __ = nil; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_type(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_type\n"));
  {
#line 313
  __ = newCtype(DOUBLE);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_type(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_type\n"));
  {
#line 312
  __ = newCtype(FLOAT);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_type(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_type\n"));
  {
#line 311
  __ = newCtype(INT);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_symbol(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_symbol\n"));
  {
#line 308
  __ = newSymbol(yytext);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_empty(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_empty\n"));
  {
#line 306
  __ = newSymbol(yytext) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_text(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_text\n"));
  {
#line 304
  __ = newSymbol(yytext) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_stmt(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_stmt\n"));
  {
#line 300
  __ = newReturn(s);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_mkbody(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_mkbody\n"));
  {
#line 297
   __ = newBody() ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_body(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define b yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_body\n"));
  {
#line 295
   __ = b ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef b
}
YY_ACTION(void) yy_1_body(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define b yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_body\n"));
  {
#line 293
   bodyAppend(b, s) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef b
}
YY_ACTION(void) yy_3_params(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define t yy->__val[-2]
#define p yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_params\n"));
  {
#line 289
   __ = revPrams(p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef t
#undef p
}
YY_ACTION(void) yy_2_params(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define t yy->__val[-2]
#define p yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_params\n"));
  {
#line 286
   p = newParams(t,s,p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef t
#undef p
}
YY_ACTION(void) yy_1_params(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define t yy->__val[-2]
#define p yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_params\n"));
  {
#line 285
   p = newParams(t,s,p) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
#undef t
#undef p
}
YY_ACTION(void) yy_1_function(yycontext *yy, char *yytext, int yyleng)
{
#define b yy->__val[-1]
#define p yy->__val[-2]
#define s yy->__val[-3]
#define t yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_function\n"));
  {
#line 282
   __ = newFunction(t,s,p,b) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef b
#undef p
#undef s
#undef t
}
YY_ACTION(void) yy_2_exp(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_exp\n"));
  {
#line 280
   __ = newInclude(s,1);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_1_exp(yycontext *yy, char *yytext, int yyleng)
{
#define s yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_exp\n"));
  {
#line 279
   __ = newInclude(s,0);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef s
}
YY_ACTION(void) yy_4_define(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define s yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_define\n"));
  {
#line 274
   result = e ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef s
}
YY_ACTION(void) yy_3_define(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define s yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_define\n"));
  {
#line 273
  __ = s;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef s
}
YY_ACTION(void) yy_2_define(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define s yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_define\n"));
  {
#line 273
  appendContents(s,e);
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef s
}
YY_ACTION(void) yy_1_define(yycontext *yy, char *yytext, int yyleng)
{
#define e yy->__val[-1]
#define s yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_define\n"));
  {
#line 273
   s = newContents(s) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef e
#undef s
}
YY_ACTION(void) yy_3_start(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_start\n"));
  {
#line 270
   printf("syntax error [%s]\n",yytext);exit(0); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
}
YY_ACTION(void) yy_2_start(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_start\n"));
  {
#line 269
   result = nil ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
}
YY_ACTION(void) yy_1_start(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_start\n"));
  {
#line 268
  result=d;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
}

YY_RULE(int) yy_blank(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "blank"));  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "blank", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "blank", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_space(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "space"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l4:;	
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;  if (!yy_space(yy)) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_alnum(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alnum"));
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l8;  goto l7;
  l8:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, '_')) goto l6;
  }
  l7:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "alnum", yy->__buf+yy->__pos));
  return 1;
  l6:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alnum", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_sym(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "sym"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\077\000\170\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  yyprintf((stderr, "  ok   %s @ %s\n", "sym", yy->__buf+yy->__pos));
  return 1;
  l9:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sym", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_num(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "num"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l10;
  yyprintf((stderr, "  ok   %s @ %s\n", "num", yy->__buf+yy->__pos));
  return 1;
  l10:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "num", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alpha(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alpha"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_empty(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "empty"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l12;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l12;
  l13:;	
  {  int yypos14= yy->__pos, yythunkpos14= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;  goto l13;
  l14:;	  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l12;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_empty, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "empty", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "empty", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_text(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "text"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l15;
#undef yytext
#undef yyleng
  }
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;  if (!yy_alpha(yy)) goto l19;  goto l18;
  l19:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;  if (!yy_num(yy)) goto l20;  goto l18;
  l20:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;  if (!yy_sym(yy)) goto l15;
  }
  l18:;	
  l16:;	
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;  if (!yy_alpha(yy)) goto l22;  goto l21;
  l22:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;  if (!yy_num(yy)) goto l23;  goto l21;
  l23:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;  if (!yy_sym(yy)) goto l17;
  }
  l21:;	  goto l16;
  l17:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l15;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_text, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "text", yy->__buf+yy->__pos));
  return 1;
  l15:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "text", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RET(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RET"));  if (!yymatchString(yy, "return")) goto l24;  if (!yy__(yy)) goto l24;
  yyprintf((stderr, "  ok   %s @ %s\n", "RET", yy->__buf+yy->__pos));
  return 1;
  l24:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RET", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RBRA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RBRA"));  if (!yymatchChar(yy, '}')) goto l25;
  yyprintf((stderr, "  ok   %s @ %s\n", "RBRA", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RBRA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_stmt(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "stmt"));
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yy_body(yy)) goto l28;  goto l27;
  l28:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yy_RET(yy)) goto l29;  if (!yy_symbol(yy)) goto l29;  yyDo(yy, yySet, -1, 0);  if (!yy_SEMI(yy)) goto l29;  yyDo(yy, yy_1_stmt, yy->__begin, yy->__end);  goto l27;
  l29:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yy_text(yy)) goto l30;  goto l27;
  l30:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yy_empty(yy)) goto l26;
  }
  l27:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "stmt", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l26:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "stmt", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mkbody(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "mkbody"));  yyDo(yy, yy_1_mkbody, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mkbody", yy->__buf+yy->__pos));
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mkbody", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LBRA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LBRA"));  if (!yymatchChar(yy, '{')) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "LBRA", yy->__buf+yy->__pos));
  return 1;
  l32:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LBRA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RPAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RPAR"));  if (!yymatchChar(yy, ')')) goto l33;  if (!yy__(yy)) goto l33;
  yyprintf((stderr, "  ok   %s @ %s\n", "RPAR", yy->__buf+yy->__pos));
  return 1;
  l33:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RPAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COMMA(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMA"));  if (!yymatchChar(yy, ',')) goto l34;  if (!yy__(yy)) goto l34;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 1;
  l34:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMA", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LPAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LPAR"));  if (!yymatchChar(yy, '(')) goto l35;  if (!yy__(yy)) goto l35;
  yyprintf((stderr, "  ok   %s @ %s\n", "LPAR", yy->__buf+yy->__pos));
  return 1;
  l35:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LPAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_mkNil(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "mkNil"));  yyDo(yy, yy_1_mkNil, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "mkNil", yy->__buf+yy->__pos));
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "mkNil", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SEMI(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SEMI"));  if (!yymatchChar(yy, ';')) goto l37;  if (!yy__(yy)) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "SEMI", yy->__buf+yy->__pos));
  return 1;
  l37:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEMI", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_body(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "body"));  if (!yy_LBRA(yy)) goto l38;  if (!yy_mkbody(yy)) goto l38;  yyDo(yy, yySet, -2, 0);  if (!yy_stmt(yy)) goto l38;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_body, yy->__begin, yy->__end);
  l39:;	
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yy_stmt(yy)) goto l40;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_body, yy->__begin, yy->__end);  goto l39;
  l40:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;
  }  if (!yy_RBRA(yy)) goto l38;  yyDo(yy, yy_2_body, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "body", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l38:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "body", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_params(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "params"));  if (!yy_LPAR(yy)) goto l41;  if (!yy_mkNil(yy)) goto l41;  yyDo(yy, yySet, -3, 0);
  {  int yypos42= yy->__pos, yythunkpos42= yy->__thunkpos;  if (!yy_type(yy)) goto l42;  yyDo(yy, yySet, -2, 0);  if (!yy_symbol(yy)) goto l42;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_params, yy->__begin, yy->__end);
  l44:;	
  {  int yypos45= yy->__pos, yythunkpos45= yy->__thunkpos;  if (!yy_COMMA(yy)) goto l45;  if (!yy_type(yy)) goto l45;  yyDo(yy, yySet, -2, 0);  if (!yy_symbol(yy)) goto l45;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_params, yy->__begin, yy->__end);  goto l44;
  l45:;	  yy->__pos= yypos45; yy->__thunkpos= yythunkpos45;
  }  goto l43;
  l42:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;
  }
  l43:;	  if (!yy_RPAR(yy)) goto l41;  yyDo(yy, yy_3_params, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "params", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "params", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_type(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "type"));
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yymatchString(yy, "int")) goto l48;  if (!yy__(yy)) goto l48;  yyDo(yy, yy_1_type, yy->__begin, yy->__end);  goto l47;
  l48:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchString(yy, "float")) goto l49;  if (!yy__(yy)) goto l49;  yyDo(yy, yy_2_type, yy->__begin, yy->__end);  goto l47;
  l49:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchString(yy, "double")) goto l46;  if (!yy__(yy)) goto l46;  yyDo(yy, yy_3_type, yy->__begin, yy->__end);
  }
  l47:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "type", yy->__buf+yy->__pos));
  return 1;
  l46:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "type", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DQUOTE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DQUOTE"));  if (!yymatchChar(yy, '\"')) goto l50;
  yyprintf((stderr, "  ok   %s @ %s\n", "DQUOTE", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DQUOTE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RSQ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RSQ"));  if (!yymatchChar(yy, '>')) goto l51;
  yyprintf((stderr, "  ok   %s @ %s\n", "RSQ", yy->__buf+yy->__pos));
  return 1;
  l51:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RSQ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_HEAD(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "HEAD"));  if (!yymatchString(yy, ".h")) goto l52;
  yyprintf((stderr, "  ok   %s @ %s\n", "HEAD", yy->__buf+yy->__pos));
  return 1;
  l52:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HEAD", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LSQ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LSQ"));  if (!yymatchChar(yy, '<')) goto l53;
  yyprintf((stderr, "  ok   %s @ %s\n", "LSQ", yy->__buf+yy->__pos));
  return 1;
  l53:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LSQ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_INCL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "INCL"));  if (!yymatchString(yy, "#include")) goto l54;  if (!yy__(yy)) goto l54;
  yyprintf((stderr, "  ok   %s @ %s\n", "INCL", yy->__buf+yy->__pos));
  return 1;
  l54:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INCL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_function(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 4, 0);
  yyprintf((stderr, "%s\n", "function"));  if (!yy_type(yy)) goto l55;  yyDo(yy, yySet, -4, 0);  if (!yy_symbol(yy)) goto l55;  yyDo(yy, yySet, -3, 0);  if (!yy_params(yy)) goto l55;  yyDo(yy, yySet, -2, 0);
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yy_body(yy)) goto l57;  yyDo(yy, yySet, -1, 0);  goto l56;
  l57:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yy_SEMI(yy)) goto l55;  if (!yy_mkNil(yy)) goto l55;  yyDo(yy, yySet, -1, 0);
  }
  l56:;	  yyDo(yy, yy_1_function, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "function", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 4, 0);
  return 1;
  l55:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "function", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RBRACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RBRACE"));  if (!yymatchChar(yy, '}')) goto l58;  if (!yy__(yy)) goto l58;
  yyprintf((stderr, "  ok   %s @ %s\n", "RBRACE", yy->__buf+yy->__pos));
  return 1;
  l58:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RBRACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_exp(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "exp"));
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yy_function(yy)) goto l61;  goto l60;
  l61:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;  if (!yy_INCL(yy)) goto l62;  if (!yy_LSQ(yy)) goto l62;  if (!yy_symbol(yy)) goto l62;  yyDo(yy, yySet, -1, 0);  if (!yy_HEAD(yy)) goto l62;  if (!yy_RSQ(yy)) goto l62;  yyDo(yy, yy_1_exp, yy->__begin, yy->__end);  goto l60;
  l62:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;  if (!yy_INCL(yy)) goto l59;  if (!yy_DQUOTE(yy)) goto l59;  if (!yy_symbol(yy)) goto l59;  yyDo(yy, yySet, -1, 0);  if (!yy_HEAD(yy)) goto l59;  if (!yy_DQUOTE(yy)) goto l59;  yyDo(yy, yy_2_exp, yy->__begin, yy->__end);
  }
  l60:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "exp", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l59:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "exp", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LBRACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LBRACE"));  if (!yymatchChar(yy, '{')) goto l63;  if (!yy__(yy)) goto l63;
  yyprintf((stderr, "  ok   %s @ %s\n", "LBRACE", yy->__buf+yy->__pos));
  return 1;
  l63:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LBRACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_symbol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "symbol"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l64;
#undef yytext
#undef yyleng
  }  if (!yy_alpha(yy)) goto l64;
  l65:;	
  {  int yypos66= yy->__pos, yythunkpos66= yy->__thunkpos;  if (!yy_alnum(yy)) goto l66;  goto l65;
  l66:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l64;
#undef yytext
#undef yyleng
  }  if (!yy__(yy)) goto l64;  yyDo(yy, yy_1_symbol, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "symbol", yy->__buf+yy->__pos));
  return 1;
  l64:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "symbol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCENT"));  if (!yymatchChar(yy, '%')) goto l67;  if (!yy__(yy)) goto l67;
  yyprintf((stderr, "  ok   %s @ %s\n", "PCENT", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eol"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l68;
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 1;
  l68:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_define(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "define"));  if (!yy_PCENT(yy)) goto l69;  if (!yy_symbol(yy)) goto l69;  yyDo(yy, yySet, -2, 0);  if (!yy_LBRACE(yy)) goto l69;  if (!yy_bln(yy)) goto l69;  yyDo(yy, yy_1_define, yy->__begin, yy->__end);  if (!yy_bln(yy)) goto l69;  if (!yy_exp(yy)) goto l69;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_define, yy->__begin, yy->__end);
  l70:;	
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yy_bln(yy)) goto l71;  if (!yy_exp(yy)) goto l71;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_define, yy->__begin, yy->__end);  goto l70;
  l71:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;
  }  yyDo(yy, yy_3_define, yy->__begin, yy->__end);  if (!yy_bln(yy)) goto l69;  if (!yy_RBRACE(yy)) goto l69;  if (!yy_PCENT(yy)) goto l69;  yyDo(yy, yy_4_define, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "define", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l69:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "define", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bln(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "bln"));
  l73:;	
  {  int yypos74= yy->__pos, yythunkpos74= yy->__thunkpos;  if (!yy_blank(yy)) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos74; yy->__thunkpos= yythunkpos74;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "bln", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos76= yy->__pos, yythunkpos76= yy->__thunkpos;  if (!yy_bln(yy)) goto l77;  if (!yy_define(yy)) goto l77;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_start, yy->__begin, yy->__end);  goto l76;
  l77:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;
  {  int yypos79= yy->__pos, yythunkpos79= yy->__thunkpos;  if (!yymatchDot(yy)) goto l79;  goto l78;
  l79:;	  yy->__pos= yypos79; yy->__thunkpos= yythunkpos79;
  }  yyDo(yy, yy_2_start, yy->__begin, yy->__end);  goto l76;
  l78:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l75;
#undef yytext
#undef yyleng
  }
  l80:;	
  {  int yypos81= yy->__pos, yythunkpos81= yy->__thunkpos;
  {  int yypos82= yy->__pos, yythunkpos82= yy->__thunkpos;  if (!yy_eol(yy)) goto l82;  goto l81;
  l82:;	  yy->__pos= yypos82; yy->__thunkpos= yythunkpos82;
  }
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yymatchDot(yy)) goto l81;  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }  if (!yymatchDot(yy)) goto l81;  goto l80;
  l81:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l75;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_start, yy->__begin, yy->__end);
  }
  l76:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l75:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 348 "cParser.leg"

;
char* to_cap(const char *text) {
    // ワイド文字列のメモリ確保 (最大3倍のサイズを確保)
    size_t length = strlen(text);
    char* bold_text = malloc(length + 1);  // ワイド文字を使うため、余裕を持たせます
    
    if (bold_text == NULL) {
        fprintf(stderr, "Memory allocation failed\n");
        return NULL;
    }
    
    char*p = bold_text;  // 書き込み用のポインタ

    while (*text) {
        if (*text >= 'a' && *text <= 'z') {
            *p++ = *text - 32;  // a-z の太字フォント
        } else {
            *p++ = *text;  // その他の文字はそのまま
        }
        text++;
    }
    *p = '\0';  // 終端文字

    return bold_text;
}

char* moduleName = 0;

tkn evaluate(tkn token){
    switch (getType(token))
    {
        case Contents:{
            int size = get(token,Contents,size);
            tkn* exps = get(token,Contents,expressions);
            tkn name = get(token,Contents,name);
            moduleName = get(name,Symbol,name);
            write("/* %s module */\n\n",moduleName);
            for(int i = 0; i<size; i++){
                evaluate(exps[i]);
            }
            break;
        }
        case Include:{
            tkn header = token->Include.header;
            if(token->Include.custom==0){
                write("#include <%s.h>\n",get(header,Symbol,name));
            }else{
                write("#include \"%s.h\"\n",get(header,Symbol,name));
            }
            break;
        }
        case Function:{
            addFunction(token);
            tkn retType = get(token,Function,retType);
            tkn name = get(token,Function,name);
            tkn params = get(token,Function,params);
            tkn body = get(token,Function,body);
            write("\n\n%s %s",CtypeToStr(get(retType,Ctype,typeC)),get(name,Symbol,name));
            if(params!=nil)evaluate(params);
            else write("()");
            if(body==nil)write(";");
            else evaluate(body);
            break;
        }
        case Params:{
            write("(");
            if(token!=nil){
                write("%s %s",CtypeToStr(get(token->Params.paramsType,Ctype,typeC)),get(token->Params.paramsName,Symbol,name));
                token = token->Params.paramNext;
                while(token!=nil){
                    write(",%s %s",CtypeToStr(get(token->Params.paramsType,Ctype,typeC)),get(token->Params.paramsName,Symbol,name));
                    token = token->Params.paramNext;
                }
            }
            write(")");
            break;
        }
        case Body:{
            tkn *stmt = get(token, Body, statements);
            unsigned int size = get(token, Body, size);
            write("{");
            for(int i=0; i<size; i++){
                evaluate(stmt[i]);
            }
            write("}");
            break;
        }
        case Return:{
            tkn variable = get(token,Return,variable);
            write("return %s;",get(variable,Symbol,name));
            break;
        }
        case Symbol:{
            char* name = get(token,Symbol,name);
            write("%s",name);
            break;
        }
        default:{
            DEBUG_ERROR("this is not happen type[%d]",getType(token));
            break;
        }
    }
    return nil;
}


int main(int argc, char **argv)
{
    _file_ = fopen("output.c", "w");
    if (!_file_) {
        perror("Failed to open file");
        return 1;
    }
    write("\n\n//------< START SHICA WRAP EXE> -------------------\n\n");//REMOVEME
    
    //parse, copy and pasete code
    while (cLangParse()){
        if(result==nil)break;
        evaluate(result);
    }

    
    char **funcList = 0;
    //make interface enum list
    if(nfunctions>0){
        
        funcList = realloc(funcList,sizeof(char*) * nfunctions);
        write("\n\nenum{\n");
        for(int i=0; i<nfunctions; i++){
            char* name = get(get(functions[i],Function,name),Symbol,name);
            char* cap  = to_cap(name);
            funcList[i] = cap;
            write("     __%s__P,\n",cap);
        }
        write("}%s;\n",to_cap(moduleName));

        //make SHICA interface function
        for(int i=0; i<nfunctions; i++){
            tkn retType = get(functions[i],Function,retType);
            tkn name = get(functions[i],Function,name);
            tkn params = get(functions[i],Function,params);
            write("\n\nvoid %s_%s(oop process, oop GM){\n",moduleName,get(name,Symbol,name));
            tkn dup = params;
            while(dup!=nil){
                char *typeC = CtypeToStr(get(dup->Params.paramsType,Ctype,typeC));
                write("     %s %s = get%s();\n",typeC,get(dup->Params.paramsName,Symbol,name),typeC);
                dup = dup->Params.paramNext;
            }
            write("     Array_push(mstack, %s(",get(name,Symbol,name));
            if(params!=nil){
                dup = params;
                write("%s",get(dup->Params.paramsName,Symbol,name));
                dup = dup->Params.paramNext;
                while(dup!=nil){
                    write(",%s",get(dup->Params.paramsName,Symbol,name));
                    dup = dup->Params.paramNext;
                }
            }
            write("));\n     return;\n}");
        }
        //make module function
        write("\n\nvoid user_lib_%s(oop process,oop GM){\n",moduleName);
        write("     getInt(mpc);\n     int func_num = int value;\n");
        write("     switch(func_num){\n");
        for(int i=0; i<nfunctions; i++){
        char* name = get(get(functions[i],Function,name),Symbol,name);
        write("         case __%s__P: %s_%s(process, GM); break;\n",funcList[i],moduleName,name);
        }
        write("         defualt:DEBUG_ERROR(\"this is not happen\");\n");
        write("     }\n");
        write("}\n");
    }
    write("\n\n//------< END  SHICA WRAP EXE> -------------------\n");//REMOVEME

    write("\n\n//------< START SHICA WRAP COMP> -------------------\n");

    write("\n\nenum{\n");
    for(int i=0; i<nfunctions; i++){
        char* name = get(get(functions[i],Function,name),Symbol,name);
        char* cap  = to_cap(name);
        funcList[i] = cap;
        write("     __%s__P,\n",cap);
    }
    write("}%s;\n",to_cap(moduleName));
    write("\nvoid setting_userlib_%s(){\n",moduleName);
    //PRIM FUNCTION
    for(int i=0; i<nfunctions; i++){
        tkn retType = get(functions[i],Function,retType);
        tkn name = get(functions[i],Function,name);
        tkn params = get(functions[i],Function,params);
        int sizeOfParams = 0;
        tkn dup = params;
        while(dup!=nil){sizeOfParams++;dup = dup->Params.paramNext;}
        write("     newPrimitive(%s,USERLIB,%s_P,%s",get(name,Symbol,name),funcList[i],CtypeToShicaStr(get(retType,Ctype,typeC)),sizeOfParams);
        while(params!=nil){
            write(",%s",CtypeToShicaStr(get(params->Params.paramsType,Ctype,typeC)));
            params = params->Params.paramNext;
        }
        write(");\n");
    }
    write("}\n");
    write("\n\n//------< END SHICA WRAP COMP> -------------------\n");
    //EVENT FUNCTION
    
    return 0;
}

