
#ifndef COMMUNICATE_H
#define COMMUNICATE_H

extern enum COMMUNICATE_E{
    COMMUNICATE_WiFi_RECEIVE_E,
    COMMUNICATE_WiFi_BROADCAST_RECEIVE_E,
    COMMUNICATE_WiFi_GROUP_RECEIVE_E,
} COMMUNICATE_E;

extern enum COMMUNICATE_P{
    COMMUNICATE_WiFi_SEND_P,
    COMMUNICATE_WiFi_BROADCAST_P,
    COMMUNICATE_WiFi_GROUP_BROADCAST_P,
    COMMUNICATE_WiFi_BUILD_GROUP_P,
    COMMUNICATE_WiFi_LEAVE_GROUP_P,
} COMMUNICATE_P;

#endif