send:
	gcc -o udpSend UDPsend.c

reci:
	gcc -o udpReceive UDPreceive.c

both:
	gcc -o udpBoth UDPboth.c

udp: 
	gcc -o udpLeave udpLeave.c
gitUpdata:
	git fetch origin
	git pull origin main

daygit:
	git add .
	git commit -m "dalily commit"
	git push

gitKillUpdata:
	git reset --hard
	git fetch origin
	git reset --hard origin/main